api_hash: 6aff8a9bf1cce3db766e2ebfb9423520
api_id: 13259570
bot_token: 5420753409:AAEJTATYXvMWgEKVL-aTdISDb_vt3U3OmjU
chat:
- chat_id: HuiMouYiXiao2023
  last_read_message_id: 47000000
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
# in linux please use /
# save_path: E:\github\telegram_media_downloader
proxy:
  hostname: 127.0.0.1
  port: 7890
  scheme: socks5
disable_syslog: []
save_path: E:\Program Files\telegram_media_downloader-2.2.0\downloads
language: ZH
sess_data: 65cd9aab%2C1724045921%2C028e5%2A21CjBzSCc6iKCTqKxMJ6MIWHUEFJnaqB-hTZO5VnVRGsPiCIQCus_bZl2zWxv8eQsLgNsSVk9sblNLYzBFRTJEdm93SzZyWExlUW8zRnFXNGF2VEZhQklUUERlOWNFMnA2Um5EbnZYUTVBeTd3T1c1Z1NkLTRRVkNpTk5wak92UFpITjlnTnpQNzZ3IIEC
#upload_drive:
#  enable_upload_file: true
#  remote_dir: drive:/aliyun
#  rclone_path: D:\Programs\rclone\rclone.exe
upload_drive:
  upload_adapter: aligo
  enable_upload_file: true
  before_upload_file_zip: false
  after_upload_file_delete: true
  remote_dir: tg
